obstacle_extractor:
  use_scan: true
  use_pcl: false
  min_group_points: 3 #3
  max_group_distance: 0.1 #0.05

  # active: true
  # discard_converted_segments: true
  # transform_coordinates: true
  # distance_proportion: 0.00628
  # max_split_distance: 0.2
  # max_merge_separation: 0.2
  # max_merge_spread: 0.2
  # max_circle_radius: 0.6
  # radius_enlargement: 0.3
  # frame_id: map
